import functions as fn
import visualizations as v

# Datos generales
a1=fn.f_datos('cryptocom','BTC/USDT')
a2=fn.f_datos('cryptocom','DOGE/USDT')
a3=fn.f_datos('cryptocom','ETH/USDT')
a4=fn.f_datos('bitso','BTC/USDT')
a5=fn.f_datos('bitso','DOGE/USD')
a6=fn.f_datos('bitso','ETH/USD')
a7=fn.f_datos('bitget','BTC/USDT')
a8=fn.f_datos('bitget','DOGE/USDT')
a9=fn.f_datos('bitget','ETH/USDT')
# 1. Consumir datos de CCXT
b1=fn.f_consumo_datos(a1)
b2=fn.f_consumo_datos(a2)
b3=fn.f_consumo_datos(a3)
b4=fn.f_consumo_datos(a4)
b5=fn.f_consumo_datos(a5)
b6=fn.f_consumo_datos(a6)
b7=fn.f_consumo_datos(a7)
b8=fn.f_consumo_datos(a8)
b9=fn.f_consumo_datos(a9)
d=fn.f_diccionario(b1,b2,b3,b4,b5,b6,b7,b8)
# 2. Visualización de Microestructura
c1=fn.f_datos_2(a1)
c2=fn.f_datos_2(a2)
c3=fn.f_datos_2(a3)
c4=fn.f_datos_2(a4)
c5=fn.f_datos_2(a5)
c6=fn.f_datos_2(a6)
c7=fn.f_datos_2(a7)
c8=fn.f_datos_2(a8)
c9=fn.f_datos_2(a9)
vm=fn.f_visualizacion_microestructura(c1,c2,c3,c4,c5,c6,c7,c8,c9)
g1=v.f_grafica(c1,c2,c3,c4,c5,c6,c7,c8,c9)
# 3. Modelado de Microestructura
d1=fn.f_datos_2(a1)
d2=fn.f_datos_2(a2)
d3=fn.f_datos_2(a3)
d4=fn.f_datos_2(a4)
d5=fn.f_datos_2(a5)
d6=fn.f_datos_2(a6)
d7=fn.f_datos_2(a7)
d8=fn.f_datos_2(a8)
d9=fn.f_datos_2(a9)
mm=fn.f_modelado_microestructura(d1,d2,d3,d4,d5,d6,d7,d8,d9)